"""
eval_llm_judge.py - LLM-as-Judge Evaluation with Multi-Provider Support
========================================================================
Pattern 1: Single score with reasoning

Measures GENERATION quality — is the recipe the LLM produced actually good?
Complements RAGAS which measures RETRIEVAL quality.

Scoring rubric (0-5 each):
  1. ingredient_faithfulness — did the LLM only use ingredients the user listed?
  2. coherence               — are the instructions clear and make culinary sense?
  3. relevance               — does the recipe match what the user asked for?
  4. completeness            — has dish name, cook time, ingredients, steps?

Multi-provider judge support:
  - openai   : gpt-4o-mini judges (risk: self-evaluation bias)
  - anthropic: claude-haiku-4-5 judges (cross-provider, eliminates bias)

Run with each provider and compare:
  JUDGE_PROVIDER=openai    python eval_llm_judge.py
  JUDGE_PROVIDER=anthropic python eval_llm_judge.py

Output:
  evallm_as_judge_results/llm_judge_scores_<provider>_YYYYMMDD_HHMM.csv
  evallm_as_judge_results/llm_judge_summary_<provider>.json
"""

import os
import json
import tomllib
import requests
import pandas as pd
from datetime import datetime
from pathlib import Path

# ── Config ────────────────────────────────────────────────────────────────────
secrets_path = Path(".streamlit/secrets.toml")
with open(secrets_path, "rb") as f:
    secrets = tomllib.load(f)

OPEN_AI_API_KEY   = secrets.get("OPEN_AI_API_KEY", "")
ANTHROPIC_API_KEY = secrets.get("ANTHROPIC_API_KEY", "")
BACKEND_URL       = os.environ.get("BACKEND_URL", "http://127.0.0.1:8000")

# golden_test_set.json has structured fields matching real SnapChef user inputs:
# ingredients_list, cooking_time, serving_size, prompt
# NOT synthetic_testset.csv — that has retrieval questions not user inputs
GOLDEN_SET  = Path("golden_test_set.json")
OUTPUT_DIR  = Path("evallm_as_judge_results")
OUTPUT_DIR.mkdir(exist_ok=True)

# ── Provider selection ────────────────────────────────────────────────────────
# Switch judge provider via environment variable:
#   JUDGE_PROVIDER=openai    python eval_llm_judge.py  (default)
#   JUDGE_PROVIDER=anthropic python eval_llm_judge.py  (cross-provider validation)
#
# Why cross-provider matters:
#   gpt-4o-mini generates the recipe AND judges it → self-evaluation bias
#   Claude judges gpt-4o-mini's output → independent, unbiased scoring
#   If both providers give similar scores → results are trustworthy
#   If Claude scores lower → self-evaluation bias confirmed
JUDGE_PROVIDER = os.environ.get("JUDGE_PROVIDER", "openai").lower()

def get_judge_llm():
    """
    Returns the judge LLM based on JUDGE_PROVIDER env variable.
    temperature=0 for all providers — deterministic, reproducible scoring.
    """
    if JUDGE_PROVIDER == "anthropic":
        if not ANTHROPIC_API_KEY:
            print("ERROR: ANTHROPIC_API_KEY not found in secrets.toml")
            print("Add: ANTHROPIC_API_KEY = 'sk-ant-...' to .streamlit/secrets.toml")
            exit(1)
        from langchain_anthropic import ChatAnthropic
        print(f"Judge: Claude Haiku (cross-provider — eliminates self-evaluation bias)")
        return ChatAnthropic(
            model="claude-haiku-4-5",
            anthropic_api_key=ANTHROPIC_API_KEY,
            temperature=0,
        )
    else:
        # Default: openai
        if not OPEN_AI_API_KEY:
            print("ERROR: OPEN_AI_API_KEY not found in secrets.toml")
            exit(1)
        from langchain_openai import ChatOpenAI
        print(f"Judge: GPT-4o-mini (note: same model as generator — self-evaluation bias possible)")
        return ChatOpenAI(
            model="gpt-4o-mini",
            openai_api_key=OPEN_AI_API_KEY,
            temperature=0,
        )

# ── Generation LLM (always OpenAI — same as production app) ──────────────────
def get_gen_llm():
    """
    Recipe generator — always gpt-4o-mini regardless of judge provider.
    temperature=0 for reproducible eval results.
    Note: production app uses gpt-4o — using mini here keeps eval costs low.
    """
    from langchain_openai import ChatOpenAI
    return ChatOpenAI(
        model="gpt-4o-mini",
        openai_api_key=OPEN_AI_API_KEY,
        temperature=0,
    )

# ── Judge scoring prompt ──────────────────────────────────────────────────────
JUDGE_PROMPT = """You are an expert culinary AI evaluator scoring a recipe generated by SnapChef.

SnapChef's core rule: ONLY use ingredients the user explicitly listed. Never add others.

USER REQUEST:
- Available ingredients: {ingredients}
- Preference: "{user_query}"
- Cooking time: {cooking_time}
- Servings needed: {serving_size}

GENERATED RECIPE:
{recipe}

Score on each criterion from 0 to 5:

1. ingredient_faithfulness (0-5):
   5 = uses ONLY ingredients from the user's list, zero exceptions
   4 = uses listed ingredients plus water (universally acceptable)
   3 = uses one unlisted ingredient
   1 = uses two or more unlisted ingredients
   0 = completely ignores the ingredient constraint

2. coherence (0-5):
   5 = clear steps, logical order, makes culinary sense throughout
   3 = some steps unclear or slightly out of order
   0 = instructions confusing, contradictory, or impossible to follow

3. relevance (0-5):
   5 = perfectly matches the user's request and fits within cooking time
   3 = partially matches but misses some aspects of the request
   0 = unrelated to what the user asked for

4. completeness (0-5):
   5 = has dish name, cook time, full ingredient list, step-by-step instructions
   3 = missing one required section
   0 = missing multiple sections or just a vague description

Be strict and honest. A score of 5 should be genuinely excellent, not just adequate.
If the recipe adds ANY ingredient not in the user's list, ingredient_faithfulness cannot be 5.

Reply in this EXACT format — JSON only, no other text, no markdown code blocks:
{{"ingredient_faithfulness": X, "coherence": X, "relevance": X, "completeness": X, "overall": X, "reasoning": "one sentence explaining the key strengths and weaknesses"}}

Where overall = average of the four scores rounded to 1 decimal place."""


# ── Step 1: Retrieve recipes from backend ─────────────────────────────────────
def retrieve_recipes(query: str, n: int = 10) -> list[dict]:
    """Same GET /search call as the Streamlit app. n=10 matches production."""
    try:
        resp = requests.get(
            f"{BACKEND_URL}/search",
            params={"query": query, "n": n},
            timeout=30,
        )
        resp.raise_for_status()
        return resp.json()
    except Exception as e:
        print(f"  ⚠️  Backend error: {e}")
        return []


# ── Step 2: Format context ─────────────────────────────────────────────────────
def format_recipe_summary(recipes: list[dict]) -> str:
    """Mirrors recipe_summary block in GenerateRecipe.py exactly."""
    summary = ""
    for i, recipe in enumerate(recipes, 1):
        title    = recipe.get("name", "Untitled")
        servings = recipe.get("servings", "N/A")
        desc     = recipe.get("description", "")
        ings     = recipe.get("ingredients_raw", [])
        if isinstance(ings, str):
            ings = [ings]
        elif ings is None:
            ings = []
        steps = recipe.get("steps", "") or "No steps provided."
        summary += (
            f"{i}. {title} — serves {servings}\n"
            f"   Description: {desc}\n"
            f"   Ingredients: {', '.join(ings)}\n"
            f"   Steps: {steps}\n\n"
        )
    return summary


# ── Step 3: Generate recipe ────────────────────────────────────────────────────
def generate_recipe(
    prompt_text:      str,
    ingredients_list: list[str],
    cooking_time:     str,
    serving_size:     int,
    recipe_summary:   str,
    gen_llm,
) -> str:
    """Mirrors build_llm_prompt() in GenerateRecipe.py exactly."""
    prompt = f"""The user wants: "{prompt_text}".

Retrieved recipes for inspiration:
{recipe_summary}

STRICT RULES:
1. ONLY use these ingredients: {', '.join(ingredients_list)}
2. Do NOT add any other ingredients, not even pantry staples like salt or oil
3. If a step needs something unavailable, skip it or substitute from the user's list
4. If ingredients are too limited, make the simplest possible dish and explain honestly

Create a recipe for {serving_size} servings within {cooking_time}.

Format in clean markdown:

# 🍽️ [Dish Name]

**⏱️ Cook time:** X minutes

---

## 🛒 Ingredients (serves {serving_size})
- only list ingredients from the user's available list

---

## 👨‍🍳 Instructions
1. Step one
2. Step two

---

> 💡 **Tip:** [one practical tip]"""

    return gen_llm.invoke(prompt).content


# ── Step 4: Judge the recipe ───────────────────────────────────────────────────
def judge_recipe(
    prompt_text:      str,
    ingredients_list: list[str],
    cooking_time:     str,
    serving_size:     int,
    recipe:           str,
    judge_llm,
) -> dict:
    """
    Score the recipe using the judge LLM.
    The judge reads query + recipe TOGETHER — more accurate than embedding similarity.
    This is why LLM-as-judge catches things RAGAS misses.
    """
    prompt = JUDGE_PROMPT.format(
        ingredients  = ", ".join(ingredients_list),
        user_query   = prompt_text,
        cooking_time = cooking_time,
        serving_size = serving_size,
        recipe       = recipe,
    )

    response = judge_llm.invoke(prompt)

    try:
        content = response.content.strip()
        # Strip markdown code blocks if judge wraps in ```json
        if content.startswith("```"):
            content = content.split("```")[1]
            if content.startswith("json"):
                content = content[4:]
            content = content.strip()
        return json.loads(content)
    except json.JSONDecodeError:
        # Try extracting JSON if there's surrounding text
        content = response.content
        start = content.find("{")
        end   = content.rfind("}") + 1
        if start != -1 and end > start:
            try:
                return json.loads(content[start:end])
            except Exception:
                pass
        print(f"  ⚠️  Could not parse judge response: {content[:100]}")
        return {
            "ingredient_faithfulness": 0,
            "coherence":               0,
            "relevance":               0,
            "completeness":            0,
            "overall":                 0,
            "reasoning":               "parse error",
        }


# ── Main evaluation loop ───────────────────────────────────────────────────────
def run_llm_judge_eval():
    print("=" * 60)
    print("SnapChef LLM-as-Judge Evaluation")
    print("=" * 60)

    judge_llm = get_judge_llm()
    gen_llm   = get_gen_llm()

    print(f"Generator: GPT-4o-mini (same as production app)")
    print(f"Test set:  golden_test_set.json (real SnapChef user inputs)\n")

    if not GOLDEN_SET.exists():
        print(f"ERROR: {GOLDEN_SET} not found in project root.")
        exit(1)

    with open(GOLDEN_SET) as f:
        test_cases = json.load(f)

    print(f"Loaded {len(test_cases)} test cases\n")

    results = []

    for i, tc in enumerate(test_cases, 1):
        ingredients_list = tc["ingredients_list"]
        cooking_time     = tc["cooking_time"]
        serving_size     = tc["serving_size"]
        prompt_text      = tc["prompt"]

        label = prompt_text if prompt_text else ', '.join(ingredients_list[:3])
        print(f"[{i:02d}/{len(test_cases)}] {label[:55]}")

        # Build query same as GenerateRecipe.py
        query = (
            f"{prompt_text} that can be made with "
            f"{', '.join(ingredients_list)} and takes {cooking_time}."
        ).strip()

        # Step 1: Retrieve
        recipes = retrieve_recipes(query, n=10)
        if not recipes:
            print("         ⚠️  No recipes retrieved — skipping")
            continue

        # Step 2: Format context
        recipe_summary = format_recipe_summary(recipes)

        # Step 3: Generate (always GPT-4o-mini)
        recipe = generate_recipe(
            prompt_text, ingredients_list, cooking_time,
            serving_size, recipe_summary, gen_llm
        )

        # Step 4: Judge (provider depends on JUDGE_PROVIDER env var)
        scores = judge_recipe(
            prompt_text, ingredients_list, cooking_time,
            serving_size, recipe, judge_llm
        )

        results.append({
            "test_case":               i,
            "ingredients":             ', '.join(ingredients_list),
            "cooking_time":            cooking_time,
            "serving_size":            serving_size,
            "prompt":                  prompt_text,
            "generated_recipe":        recipe[:300] + "...",
            "ingredient_faithfulness": scores.get("ingredient_faithfulness", 0),
            "coherence":               scores.get("coherence", 0),
            "relevance":               scores.get("relevance", 0),
            "completeness":            scores.get("completeness", 0),
            "overall":                 scores.get("overall", 0),
            "reasoning":               scores.get("reasoning", ""),
        })

        print(
            f"         ✓  faithfulness={scores.get('ingredient_faithfulness')}/5  "
            f"coherence={scores.get('coherence')}/5  "
            f"relevance={scores.get('relevance')}/5  "
            f"overall={scores.get('overall')}/5"
        )

    # ── Save results ───────────────────────────────────────────────────────────
    results_df = pd.DataFrame(results)
    timestamp  = datetime.now().strftime('%Y%m%d_%H%M')
    csv_path   = OUTPUT_DIR / f"llm_judge_scores_{JUDGE_PROVIDER}_{timestamp}.csv"
    results_df.to_csv(csv_path, index=False)

    def safe_mean(col):
        return round(float(results_df[col].mean()), 4) if len(results_df) > 0 else 0.0

    summary = {
        "timestamp":               datetime.now().isoformat(),
        "judge_provider":          JUDGE_PROVIDER,
        "judge_model":             "claude-haiku-4-5" if JUDGE_PROVIDER == "anthropic" else "gpt-4o-mini",
        "generator_model":         "gpt-4o-mini",
        "n_samples":               len(results),
        "ingredient_faithfulness": safe_mean("ingredient_faithfulness"),
        "coherence":               safe_mean("coherence"),
        "relevance":               safe_mean("relevance"),
        "completeness":            safe_mean("completeness"),
        "overall":                 safe_mean("overall"),
    }

    json_path = OUTPUT_DIR / f"llm_judge_summary_{JUDGE_PROVIDER}.json"
    with open(json_path, "w") as f:
        json.dump(summary, f, indent=2)

    # ── Print results ──────────────────────────────────────────────────────────
    print("\n" + "=" * 60)
    print(f"LLM-AS-JUDGE RESULTS — {JUDGE_PROVIDER.upper()} judge (out of 5)")
    print("=" * 60)
    print(f"  ingredient_faithfulness : {summary['ingredient_faithfulness']:.2f}/5")
    print(f"  coherence               : {summary['coherence']:.2f}/5")
    print(f"  relevance               : {summary['relevance']:.2f}/5")
    print(f"  completeness            : {summary['completeness']:.2f}/5")
    print(f"  ─────────────────────────────────────")
    print(f"  overall                 : {summary['overall']:.2f}/5")
    print("=" * 60)
    print(f"\nPer-question scores → {csv_path}")
    print(f"Summary             → {json_path}")

    # ── Cross-provider comparison hint ─────────────────────────────────────────
    other_provider = "anthropic" if JUDGE_PROVIDER == "openai" else "openai"
    other_summary  = OUTPUT_DIR / f"llm_judge_summary_{other_provider}.json"
    if other_summary.exists():
        with open(other_summary) as f:
            other = json.load(f)
        print(f"\nCROSS-PROVIDER COMPARISON:")
        print(f"  {'Metric':<28} {'OpenAI':>8} {'Anthropic':>10} {'Diff':>8}")
        print(f"  {'─'*28} {'─'*8} {'─'*10} {'─'*8}")
        for metric in ["ingredient_faithfulness", "coherence", "relevance", "completeness", "overall"]:
            openai_score    = summary[metric] if JUDGE_PROVIDER == "openai" else other[metric]
            anthropic_score = summary[metric] if JUDGE_PROVIDER == "anthropic" else other[metric]
            diff            = anthropic_score - openai_score
            diff_str        = f"{diff:+.2f}"
            print(f"  {metric:<28} {openai_score:>8.2f} {anthropic_score:>10.2f} {diff_str:>8}")
        print()
        if abs(summary["overall"] - other["overall"]) < 0.3:
            print("  ✅ Scores consistent across providers — results are trustworthy")
        else:
            print("  ⚠️  Score gap > 0.3 — self-evaluation bias detected in OpenAI judge")
            print("     Use Anthropic scores as the more reliable baseline")
    else:
        print(f"\nTip: Run with {other_provider} judge to validate:")
        print(f"  JUDGE_PROVIDER={other_provider} python eval_llm_judge.py")

    # ── Diagnosis ──────────────────────────────────────────────────────────────
    print("\nDIAGNOSIS:")
    issues = False
    if summary["ingredient_faithfulness"] < 3.5:
        print("  ⚠️  Low ingredient faithfulness — LLM adding unlisted ingredients")
        print("     Fix: tighten STRICT RULES in generation prompt")
        issues = True
    if summary["coherence"] < 3.5:
        print("  ⚠️  Low coherence — instructions unclear or illogical")
        issues = True
    if summary["relevance"] < 3.5:
        print("  ⚠️  Low relevance — recipes don't match requests")
        issues = True
    if summary["completeness"] < 3.5:
        print("  ⚠️  Low completeness — missing required sections")
        issues = True
    if not issues:
        print("  ✅  All criteria above 3.5/5 — recipe generation quality is good")

    return summary


if __name__ == "__main__":
    run_llm_judge_eval()